"""Constants for the Unofficial Lava Lamp integration."""

DOMAIN = "lava_lamp"
DEFAULT_BASE_URL = "https://api.neurolavalamp.com"

CONF_URL = "url"
CONF_EMIT_DELAY_SECONDS = "emit_delay_seconds"
DEFAULT_EMIT_DELAY_SECONDS = 0.0

FAST_POLL_INTERVAL = 0.25
OFFLINE_POLL_INTERVAL = 30.0
SSE_RETRY_INTERVAL = 60.0
HEARTBEAT_TIMEOUT = 60.0
INITIAL_ERROR_BACKOFF = 1.0
MAX_ERROR_BACKOFF = 60.0
ERROR_LOG_INTERVAL = 300.0
